Wind:
  overwrite: false
  split: false

CF_Wind:
  overwrite: false
  split: false
  use_power_curve_5: true
  
CF_PV:
  overwrite: false
  split: false

Dunkelflaute:
  overwrite: false
  split: false

TAS:
  overwrite: false
  split: false

RSDS:
  overwrite: false
  split: false